### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "09575c0e635748c79f5accd1a3b257cd",
  "accountNumber": "1000000000",
  "amount": 1000000
}

### get transaction
GET http://localhost:8080/transaction/dd89eacc210b4cb79c267aab2a3d6fbd
